In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../datasets/pizza_delivery.csv")

In [3]:
df.head()

,day,date,time,operator,branch,driver,temperature,bill,pizzas,free_wine,got_wine,discount_customer
0,Thursday,01-May-14,35.128367,Laura,East,Bruno,68.287716,58.4,4,0,0,1
1,Thursday,01-May-14,25.203074,Melissa,East,Salvatore,70.997791,26.4,2,0,0,0
2,Thursday,01-May-14,45.643404,Melissa,West,Salvatore,53.394145,58.1,3,1,0,0
3,Thursday,01-May-14,29.374298,Melissa,East,Salvatore,70.306596,35.2,3,0,0,0
4,Thursday,01-May-14,29.994610,Melissa,West,Salvatore,71.501688,38.4,2,0,0,0

**Dimensions**

In [4]:
df.ndim

2

In [5]:
df.values

array([['Thursday', '01-May-14', 35.12836705, ..., 0, 0, 1],
       ['Thursday', '01-May-14', 25.20307368, ..., 0, 0, 0],
       ['Thursday', '01-May-14', 45.64340414, ..., 1, 0, 0],
       ...,
       ['Saturday', '31-May-14', 33.14008002, ..., 0, 0, 1],
       ['Saturday', '31-May-14', 36.88054621, ..., 0, 0, 1],
       ['Saturday', '31-May-14', 35.73753383, ..., 0, 0, 0]], dtype=object)

In [6]:
df.size

15192

In [7]:
df.shape

(1266, 12)

In [8]:
cdf =  df.convert_dtypes()

In [9]:
cdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1266 entries, 0 to 1265
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   day                1266 non-null   string
 1   date               1266 non-null   string
 2   time               1266 non-null   Float64
 3   operator           1266 non-null   string
 4   branch             1266 non-null   string
 5   driver             1266 non-null   string
 6   temperature        1266 non-null   Float64
 7   bill               1266 non-null   Float64
 8   pizzas             1266 non-null   Int64
 9   free_wine          1266 non-null   Int64
 10  got_wine           1266 non-null   Int64
 11  discount_customer  1266 non-null   Int64
dtypes: Float64(3), Int64(4), string(5)
memory usage: 127.5 KB

In [11]:
cdf.select_dtypes("number")

,time,temperature,bill,pizzas,free_wine,got_wine,discount_customer
0,35.128367,68.287716,58.4,4,0,0,1
1,25.203074,70.997791,26.4,2,0,0,0
2,45.643404,53.394145,58.1,3,1,0,0
3,29.374298,70.306596,35.2,3,0,0,0
4,29.99461,71.501688,38.4,2,0,0,0
...,...,...,...,...,...,...,...
1261,38.63942,63.126424,46.7,4,0,0,0
1262,33.812971,56.302727,32.0,1,0,0,0
1263,33.14008,57.977168,45.7,3,0,0,1
1264,36.880546,52.795834,39.0,5,0,0,1
1265,35.737534,58.642759,42.7,3,0,0,0

In [13]:
df.head()

,day,date,time,operator,branch,driver,temperature,bill,pizzas,free_wine,got_wine,discount_customer
0,Thursday,01-May-14,35.128367,Laura,East,Bruno,68.287716,58.4,4,0,0,1
1,Thursday,01-May-14,25.203074,Melissa,East,Salvatore,70.997791,26.4,2,0,0,0
2,Thursday,01-May-14,45.643404,Melissa,West,Salvatore,53.394145,58.1,3,1,0,0
3,Thursday,01-May-14,29.374298,Melissa,East,Salvatore,70.306596,35.2,3,0,0,0
4,Thursday,01-May-14,29.994610,Melissa,West,Salvatore,71.501688,38.4,2,0,0,0

In [14]:
df.tail()

,day,date,time,operator,branch,driver,temperature,bill,pizzas,free_wine,got_wine,discount_customer
1261,Saturday,31-May-14,38.639420,Laura,West,Mario,63.126424,46.7,4,0,0,0
1262,Saturday,31-May-14,33.812971,Laura,East,Domenico,56.302727,32.0,1,0,0,0
1263,Saturday,31-May-14,33.140080,Laura,Centre,Luigi,57.977168,45.7,3,0,0,1
1264,Saturday,31-May-14,36.880546,Laura,Centre,Salvatore,52.795834,39.0,5,0,0,1
1265,Saturday,31-May-14,35.737534,Melissa,West,Bruno,58.642759,42.7,3,0,0,0

In [16]:
df.iat[0,8]

4

In [18]:
df.at[0,'pizzas']

4

**Select specific columns**

In [25]:
selected_column = ["date", "bill","temperature"]
xdf =  df[selected_column]
xdf

           date  bill  temperature
0     01-May-14  58.4    68.287716
1     01-May-14  26.4    70.997791
2     01-May-14  58.1    53.394145
3     01-May-14  35.2    70.306596
4     01-May-14  38.4    71.501688
...         ...   ...          ...
1261  31-May-14  46.7    63.126424
1262  31-May-14  32.0    56.302727
1263  31-May-14  45.7    57.977168
1264  31-May-14  39.0    52.795834
1265  31-May-14  42.7    58.642759

[1266 rows x 3 columns]

In [26]:
xdf.count()

date           1266
bill           1266
temperature    1266
dtype: int64

In [27]:
selected_column = ["date", "bill","temperature"]
xdf =  df[selected_column]
xdf

           date  bill  temperature
0     01-May-14  58.4    68.287716
1     01-May-14  26.4    70.997791
2     01-May-14  58.1    53.394145
3     01-May-14  35.2    70.306596
4     01-May-14  38.4    71.501688
...         ...   ...          ...
1261  31-May-14  46.7    63.126424
1262  31-May-14  32.0    56.302727
1263  31-May-14  45.7    57.977168
1264  31-May-14  39.0    52.795834
1265  31-May-14  42.7    58.642759

[1266 rows x 3 columns]

In [28]:
temp_above_60_filter = xdf['temperature'] > 60
temp_above_60_filter

0        True
1        True
2       False
3        True
4        True
        ...
1261     True
1262    False
1263    False
1264    False
1265    False
Name: temperature, Length: 1266, dtype: bool

In [29]:
xdf[temp_above_60_filter]

           date  bill  temperature
0     01-May-14  58.4    68.287716
1     01-May-14  26.4    70.997791
3     01-May-14  35.2    70.306596
4     01-May-14  38.4    71.501688
5     01-May-14  61.8    60.759504
...         ...   ...          ...
1253  31-May-14  48.5    66.351789
1254  31-May-14  38.9    61.445683
1255  31-May-14  52.9    64.761225
1256  31-May-14  45.6    66.164041
1261  31-May-14  46.7    63.126424

[830 rows x 3 columns]

In [33]:
xdf[xdf["temperature"]>70].count()

date           184
bill           184
temperature    184
dtype: int64

In [34]:
df.isin([30,40])

,day,date,time,operator,branch,driver,temperature,bill,pizzas,free_wine,got_wine,discount_customer
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1261,False,False,False,False,False,False,False,False,False,False,False,False
1262,False,False,False,False,False,False,False,False,False,False,False,False
1263,False,False,False,False,False,False,False,False,False,False,False,False
1264,False,False,False,False,False,False,False,False,False,False,False,False
1265,False,False,False,False,False,False,False,False,False,False,False,False

In [37]:
df["bill"].isin([10,50]).sum()

5

In [38]:
df['bill'].isin([10,50])

0       False
1       False
2       False
3       False
4       False
        ...
1261    False
1262    False
1263    False
1264    False
1265    False
Name: bill, Length: 1266, dtype: bool

In [45]:
df[df['pizzas'].isin([5,6,7,8,9])]

,day,date,time,operator,branch,driver,temperature,bill,pizzas,free_wine,got_wine,discount_customer
9,Thursday,01-May-14,37.954792,Melissa,Centre,Bruno,60.007379,44.8,5,0,0,0
15,Thursday,01-May-14,40.719208,Melissa,West,Salvatore,71.216953,41.5,6,1,1,0
25,Thursday,01-May-14,37.985761,Melissa,Centre,Bruno,49.309722,61.3,6,0,0,0
26,Thursday,01-May-14,26.355926,Laura,Centre,Salvatore,68.215742,48.9,5,0,0,0
29,Thursday,01-May-14,40.898407,Melissa,West,Salvatore,63.383025,49.6,6,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1243,Saturday,31-May-14,21.314470,Laura,East,Domenico,74.902024,29.7,5,0,0,1
1244,Saturday,31-May-14,36.735132,Laura,West,Salvatore,56.154315,55.1,7,0,0,0
1250,Saturday,31-May-14,34.233622,Laura,West,Bruno,66.914456,52.0,7,0,0,1
1251,Saturday,31-May-14,37.866782,Melissa,West,Bruno,56.229618,55.8,6,0,0,0
1264,Saturday,31-May-14,36.880546,Laura,Centre,Salvatore,52.795834,39.0,5,0,0,1

In [66]:
xxdf = xdf.copy()

In [60]:
xxdf[xxdf["temperature"] > 60]["temperature"] = "Hot"

C:\Users\manis\AppData\Local\Temp\ipykernel_20916\965871732.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xxdf[xxdf["temperature"] > 60]["temperature"] = "Hot"

In [62]:
xxdf.loc[xxdf["temperature"]>60, "temperature"] = "Hot"

In [68]:
xxdf[xxdf["temperature"] > 60]["temperature"]

0       68.287716
1       70.997791
3       70.306596
4       71.501688
5       60.759504
          ...
1253    66.351789
1254    61.445683
1255    64.761225
1256    66.164041
1261    63.126424
Name: temperature, Length: 830, dtype: float64

In [69]:
help(df.where)

Help on method where in module pandas.core.frame:

where(cond, other=<no_default>, *, inplace: 'bool' = False, axis: 'Axis | None' = None, level: 'Level' = None) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Replace values where the condition is False.

    Parameters
    ----------
    cond : bool Series/DataFrame, array-like, or callable
        Where `cond` is True, keep the original value. Where
        False, replace with corresponding value from `other`.
        If `cond` is callable, it is computed on the Series/DataFrame and
        should return boolean Series/DataFrame or array. The callable must
        not change input Series/DataFrame (though pandas doesn't check it).
    other : scalar, Series/DataFrame, or callable
        Entries where `cond` is False are replaced with
        corresponding value from `other`.
        If other is callable, it is computed on the Series/DataFrame and
        should return scalar or Series/DataFrame. The callable must not
        change input Series/DataFrame (though pandas doesn't check it).
        If not specified, entries will be filled with the corresponding
        NULL value (``np.nan`` for numpy dtypes, ``pd.NA`` for extension
        dtypes).
    inplace : bool, default False
        Whether to perform the operation in place on the data.
    axis : int, default None
        Alignment axis if needed. For `Series` this parameter is
        unused and defaults to 0.
    level : int, default None
        Alignment level if needed.

    Returns
    -------
    Same type as caller or None if ``inplace=True``.

    See Also
    --------
    :func:`DataFrame.mask` : Return an object of same shape as
        self.

    Notes
    -----
    The where method is an application of the if-then idiom. For each
    element in the calling DataFrame, if ``cond`` is ``True`` the
    element is used; otherwise the corresponding element from the DataFrame
    ``other`` is used. If the axis of ``other`` does not align with axis of
    ``cond`` Series/DataFrame, the misaligned index positions will be filled with
    False.

    The signature for :func:`DataFrame.where` differs from
    :func:`numpy.where`. Roughly ``df1.where(m, df2)`` is equivalent to
    ``np.where(m, df1, df2)``.

    For further details and examples see the ``where`` documentation in
    :ref:`indexing <indexing.where_mask>`.

    The dtype of the object takes precedence. The fill value is casted to
    the object's dtype, if this can be done losslessly.

    Examples
    --------
    >>> s = pd.Series(range(5))
    >>> s.where(s > 0)
    0    NaN
    1    1.0
    2    2.0
    3    3.0
    4    4.0
    dtype: float64
    >>> s.mask(s > 0)
    0    0.0
    1    NaN
    2    NaN
    3    NaN
    4    NaN
    dtype: float64

    >>> s = pd.Series(range(5))
    >>> t = pd.Series([True, False])
    >>> s.where(t, 99)
    0     0
    1    99
    2    99
    3    99
    4    99
    dtype: int64
    >>> s.mask(t, 99)
    0    99
    1     1
    2    99
    3    99
    4    99
    dtype: int64

    >>> s.where(s > 1, 10)
    0    10
    1    10
    2    2
    3    3
    4    4
    dtype: int64
    >>> s.mask(s > 1, 10)
    0     0
    1     1
    2    10
    3    10
    4    10
    dtype: int64

    >>> df = pd.DataFrame(np.arange(10).reshape(-1, 2), columns=['A', 'B'])
    >>> df
       A  B
    0  0  1
    1  2  3
    2  4  5
    3  6  7
    4  8  9
    >>> m = df % 3 == 0
    >>> df.where(m, -df)
       A  B
    0  0 -1
    1 -2  3
    2 -4 -5
    3  6 -7
    4 -8  9
    >>> df.where(m, -df) == np.where(m, df, -df)
          A     B
    0  True  True
    1  True  True
    2  True  True
    3  True  True
    4  True  True
    >>> df.where(m, -df) == df.mask(~m, -df)
          A     B
    0  True  True
    1  True  True
    2  True  True
    3  True  True
    4  True  True

In [72]:
 s = pd.Series(range(5))

In [73]:
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [80]:
s.where(~(s>=3), 10).where(~(s<3),100)

0    100
1    100
2    100
3     10
4     10
dtype: int64

In [81]:
temp_cat = df["temperature"]

In [84]:
hot_cond = temp_cat>60
cold_cond = temp_cat<=60

tc =  temp_cat.where(~hot_cond,"hot").where(~cold_cond,"cold")
tc

0        hot
1        hot
2       cold
3        hot
4        hot
        ...
1261     hot
1262    cold
1263    cold
1264    cold
1265    cold
Name: temperature, Length: 1266, dtype: object

In [85]:
df.insert(7,"temp_cat",tc)

In [86]:
df

,day,date,time,operator,branch,driver,temperature,temp_cat,bill,pizzas,free_wine,got_wine,discount_customer
0,Thursday,01-May-14,35.128367,Laura,East,Bruno,68.287716,hot,58.4,4,0,0,1
1,Thursday,01-May-14,25.203074,Melissa,East,Salvatore,70.997791,hot,26.4,2,0,0,0
2,Thursday,01-May-14,45.643404,Melissa,West,Salvatore,53.394145,cold,58.1,3,1,0,0
3,Thursday,01-May-14,29.374298,Melissa,East,Salvatore,70.306596,hot,35.2,3,0,0,0
4,Thursday,01-May-14,29.994610,Melissa,West,Salvatore,71.501688,hot,38.4,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1261,Saturday,31-May-14,38.639420,Laura,West,Mario,63.126424,hot,46.7,4,0,0,0
1262,Saturday,31-May-14,33.812971,Laura,East,Domenico,56.302727,cold,32.0,1,0,0,0
1263,Saturday,31-May-14,33.140080,Laura,Centre,Luigi,57.977168,cold,45.7,3,0,0,1
1264,Saturday,31-May-14,36.880546,Laura,Centre,Salvatore,52.795834,cold,39.0,5,0,0,1
1265,Saturday,31-May-14,35.737534,Melissa,West,Bruno,58.642759,cold,42.7,3,0,0,0